name: Build RAMOSS4M dylib

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-dylib:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4' # escolha qualquer disponível no runner

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer

      - name: Build dylib
        run: |
          mkdir -p build
          xcodebuild -project YourProject.xcodeproj \
                     -scheme YourScheme \
                     -configuration Release \
                     -derivedDataPath build \
                     BUILD_DIR=build \
                     OBJROOT=build \
                     SYMROOT=build \
                     DSTROOT=build \
                     BUILD_LIBRARIES_FOR_DISTRIBUTION=YES \
                     MACH_O_TYPE=mh_dylib \
                     clean build

      - name: Upload dylib
        uses: actions/upload-artifact@v4
        with:
          name: ramoss4m.dylib
          path: build/Build/Products/Release/*.dylib

