name: Build iOS IPA with RAMOSS4M dylib

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    env:
      APP_NAME: "SeuApp"            # Substitua pelo nome do seu app
      SCHEME_NAME: "SeuApp"         # Substitua pelo esquema do Xcode
      CONFIGURATION: "Release"
      EXPORT_METHOD: "ad-hoc"       # ou 'app-store' / 'enterprise'
      TEAM_ID: "XXXXXXXXXX"         # Substitua pelo seu Team ID
      SIGNING_IDENTITY: "Apple Distribution: Seu Nome (XXXXXXXXXX)" # Nome exato do certificado
      PROVISIONING_PROFILE: "Seuprofile.mobileprovision" # Nome do provisioning profile
      DYLIB_NAME: "ramoss4m.dylib"  # Sua dylib
      BUILD_DIR: "$GITHUB_WORKSPACE/build"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Xcode 15.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer

      - name: Install CocoaPods (se usar)
        run: |
          sudo gem install cocoapods
          pod install

      - name: Create build directory
        run: mkdir -p $BUILD_DIR

      - name: Build IPA
        run: |
          xcodebuild clean -scheme "$SCHEME_NAME" -configuration "$CONFIGURATION"
          xcodebuild archive \
            -scheme "$SCHEME_NAME" \
            -configuration "$CONFIGURATION" \
            -archivePath "$BUILD_DIR/$APP_NAME.xcarchive" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            CODE_SIGN_IDENTITY="$SIGNING_IDENTITY" \
            PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE"

      - name: Inject dylib
        run: |
          IPA_PATH="$BUILD_DIR/$APP_NAME.ipa"
          TEMP_DIR="$BUILD_DIR/temp"
          mkdir -p $TEMP_DIR
          cp "$BUILD_DIR/$APP_NAME.xcarchive/Products/Applications/$APP_NAME.app" -r "$TEMP_DIR/Payload/"
          mkdir -p "$TEMP_DIR/Payload/$APP_NAME.app/Frameworks"
          cp "$GITHUB_WORKSPACE/$DYLIB_NAME" "$TEMP_DIR/Payload/$APP_NAME.app/Frameworks/"
          cd $TEMP_DIR
          zip -r "../$APP_NAME.ipa" Payload
          cd ..
          rm -rf $TEMP_DIR

      - name: Export IPA
        run: |
          echo "IPA pronta em: $BUILD_DIR/$APP_NAME.ipa"

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: $APP_NAME.ipa
          path: $BUILD_DIR/$APP_NAME.ipa

