name: Build KeyCheck dylib

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Compile .dylib
        run: |
          clang -framework Foundation -framework UIKit \
          -isysroot $(xcrun --sdk iphoneos --show-sdk-path) \
          -arch arm64 -miphoneos-version-min=12.0 \
          keycheck_dylib.m -o libKeyCheck.dylib -dynamiclib

      - name: Upload compiled .dylib
        uses: actions/upload-artifact@v4.3.1
        with:
          name: libKeyCheck
          path: libKeyCheck.dylib

